// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh2eNfRTEQH5gLS45PMeWH7EtXs78w2nM',
    appId: '1:883389832495:web:8455df2d217051904515da',
    messagingSenderId: '883389832495',
    projectId: 'gdsc-4b58d',
    authDomain: 'gdsc-4b58d.firebaseapp.com',
    storageBucket: 'gdsc-4b58d.appspot.com',
    measurementId: 'G-X4C2GBTHP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSE3BElutpDlYSCxCr7xhZeTt-P-AR_Rs',
    appId: '1:883389832495:android:cf030ce18035160e4515da',
    messagingSenderId: '883389832495',
    projectId: 'gdsc-4b58d',
    storageBucket: 'gdsc-4b58d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNJuzebGffizIACkwl3Iacweo4QwDSV8M',
    appId: '1:883389832495:ios:6f4483526f44954f4515da',
    messagingSenderId: '883389832495',
    projectId: 'gdsc-4b58d',
    storageBucket: 'gdsc-4b58d.appspot.com',
    iosClientId: '883389832495-s0529hec00pmln4fvmpopfqvlsak4abr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNJuzebGffizIACkwl3Iacweo4QwDSV8M',
    appId: '1:883389832495:ios:6f4483526f44954f4515da',
    messagingSenderId: '883389832495',
    projectId: 'gdsc-4b58d',
    storageBucket: 'gdsc-4b58d.appspot.com',
    iosClientId: '883389832495-s0529hec00pmln4fvmpopfqvlsak4abr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );
}
